language: node_js
node_js:
- 0.8
before_script:
- npm install grunt-cli -g
script:
- grunt travis --verbose
env:
  global:
  - secure: H+NIN6lZNsfCtNxeZ/KAuOHfs9sCmsBi9FmQ3I1xxEBWiG4MaprUh+LoGqkn5y5rSkhrLgQ+qaukln+BtGtLoM55o5R03u2JQ61jpbSv2+UfqA4ymg9GRoFs93mATf/6lV+2SCvd1N8CAMbpJVp3bHyHPu7AhR5tCrqw9s4nGDc=
  - secure: NEPx3gN79bErXtnmwWaMoSkU/t+tTojrHiaCzdQ6S6uqIQ5Idb+JYCBCaL6cAysRrTYm2ZNQaH2oUq8Z3DKzNzLq1TjH35/i5TtHLHie0gNNQn2OlatbtN2PYx2ByJAjAmPJujFuYnK3ikhXfudR/mP0eyhqXYikXIiBafHxHfQ=
