language: node_js
node_js:
  - 0.10
before_script:
  - npm install grunt-cli browserstack-runner -g
script:
  - grunt travis --verbose
  - browserstack-runner
env:
  global:
    - BROWSERSTACK_USERNAME=modernizr
    - secure: "XO0FAAAdEsZmTeCCxWWKxGAd2BgxQg8NTpjIg3B+sgIWcz9PTvnJHxExFiEI1B1NT0f3AMjvWq3DU2RTHBUHcG1vKEQ6mwfH1lrKnUbL1PdOGjYYma0E0JNLbpDyW6y38letUnTI5WCA+fjYF5joIFEuFUf9P9lrAHYaaC8v740="
    - secure: "qV/i9OKB0d83BdvVXhSkWY9evl/c7T2k8bo55fyYlzZjeetd/W+wnOLu5Ckgd3r+CAkpkl84U4qK7Ga5VTs/w2DktcAvo1aCHPC2aUiW6IJJcvcauipYQ+MVa9FBuESKH4SRuq/vIYRDTWOlch+dD+e4x5Fn07rzon6DaeRy7Ao="
    - secure: "e54KI0o84XfI7LzYTIcrWcLhrHHcFDzQ9H7kNmyF6gxf+JeQtjvWZ6rR+EWgmLqZxIpNOUgXKCg0nqyZ3xtQ8FevV+pbxhsSPLZJfU2q5GpcFXNjxhhDXjFfSp1jcy6EJ5QAgrK1v+6tWIrrztiyr/qfT8lRctgwW67kMvznipo="
